### ISSUE TITLE
wf-bacterial-genomes  workflow not working

### ISSUE THREAD

**Issue by bunnu27** [epi2me-labs/wf-bacterial-genomes#41] opened 2024-07-26 11:51 UTC
### Operating System

Ubuntu 22.04

### Workflow Version

 N E X T F L O W   ~  version 24.04.3

### Workflow Execution

Command line

### CLI command run

nextflow run epi2me-labs/wf-bacterial-genomes –-help

### Workflow Execution - CLI Execution Profile

standard (default)

### What happened?

I have been using wf-bacterial-genomes workflow for last 2 years. It worked fine till date. However, now it started showing following erros 

"ERROR ~ Script compilation error
- file : /home/hmn/.nextflow/assets/epi2me-labs/wf-bacterial-genomes/main.nf
- cause: Invalid output definition @ line 862, column 5.
       output(results.all_out)
       ^
I checked main.nf file fow syntax error but it is perfectly fine. Still I downloaded new file from source "https://github.com/epi2me-labs/wf-bacterial-genomes/blob/master/main.nf"

Upgraded nextflow for latest version too.
Still not working for me. Need suggestions to troubleshoot.

### Relevant log output

```shell
na
```

### Were you able to successfully run the latest version of the workflow with the demo data?

yes

**Comment by cjalder** [comment] 2024-07-26 12:07
Hi @bunnu27 - The problem is actually with the latest version of the nextflow, which is incompatible with the workflow. We will update this in the next release cycle. But for now you can run by changing the Nextflow version used to execute the workflow e.g `NXF_VER=23.10.1 nextflow run epi2me-labs/wf-bacterial-genomes ...`. Hope that helps!

**Comment by julibeg** [comment] 2024-07-30 12:25
Hi @bunnu27, this should be fixed with the most recent release (v1.3.0). Please reopen this issue and let us know if you still run into the same problem. Thanks!

**Closed by julibeg** 2024-07-30 12:25 UTC
